// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Nutrio.Infrastructure.Persistence;

#nullable disable

namespace Nutrio.Infrastructure.Migrations
{
    [DbContext(typeof(NutrioDbContext))]
    [Migration("20260423140528_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nutrio.Domain.Entities.BodyMetricStamp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateOfEntry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("FatPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BodyMetricStamps", (string)null);
                });

            modelBuilder.Entity("Nutrio.Domain.Entities.FoodEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MealType")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("FoodEntries", (string)null);
                });

            modelBuilder.Entity("Nutrio.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("Nutrio.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActivityLevel")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GoogleId")
                        .HasColumnType("text");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Sex")
                        .HasColumnType("integer");

                    b.Property<decimal>("TargetWeight")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("WeightGoal")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Nutrio.Domain.Entities.BodyMetricStamp", b =>
                {
                    b.HasOne("Nutrio.Domain.Entities.User", null)
                        .WithMany("MetricStamps")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Nutrio.Domain.ValueObjects.BodyMetrics", "Metrics", b1 =>
                        {
                            b1.Property<Guid>("BodyMetricStampId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Height")
                                .HasColumnType("integer")
                                .HasColumnName("Height");

                            b1.Property<decimal>("Weight")
                                .HasColumnType("decimal(5,2)")
                                .HasColumnName("Weight");

                            b1.HasKey("BodyMetricStampId");

                            b1.ToTable("BodyMetricStamps");

                            b1.WithOwner()
                                .HasForeignKey("BodyMetricStampId");
                        });

                    b.Navigation("Metrics")
                        .IsRequired();
                });

            modelBuilder.Entity("Nutrio.Domain.Entities.FoodEntry", b =>
                {
                    b.HasOne("Nutrio.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nutrio.Domain.Entities.User", null)
                        .WithMany("FoodEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Nutrio.Domain.ValueObjects.Quantity", "Quantity", b1 =>
                        {
                            b1.Property<Guid>("FoodEntryId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("Unit");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(8,2)")
                                .HasColumnName("Grams");

                            b1.HasKey("FoodEntryId");

                            b1.ToTable("FoodEntries");

                            b1.WithOwner()
                                .HasForeignKey("FoodEntryId");
                        });

                    b.Navigation("Product");

                    b.Navigation("Quantity")
                        .IsRequired();
                });

            modelBuilder.Entity("Nutrio.Domain.Entities.Product", b =>
                {
                    b.OwnsOne("Nutrio.Domain.ValueObjects.Nutrients", "NutrientsPer100g", b1 =>
                        {
                            b1.Property<int>("ProductId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Calories")
                                .HasColumnType("decimal(8,2)")
                                .HasColumnName("Calories");

                            b1.Property<decimal>("Carbs")
                                .HasColumnType("decimal(8,2)")
                                .HasColumnName("Carbs");

                            b1.Property<decimal>("Fat")
                                .HasColumnType("decimal(8,2)")
                                .HasColumnName("Fat");

                            b1.Property<decimal>("Fiber")
                                .HasColumnType("decimal(8,2)")
                                .HasColumnName("Fiber");

                            b1.Property<decimal>("Protein")
                                .HasColumnType("decimal(8,2)")
                                .HasColumnName("Protein");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.Navigation("NutrientsPer100g")
                        .IsRequired();
                });

            modelBuilder.Entity("Nutrio.Domain.Entities.User", b =>
                {
                    b.OwnsOne("Nutrio.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("Email");

                            b1.HasKey("UserId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Email")
                        .IsRequired();
                });

            modelBuilder.Entity("Nutrio.Domain.Entities.User", b =>
                {
                    b.Navigation("FoodEntries");

                    b.Navigation("MetricStamps");
                });
#pragma warning restore 612, 618
        }
    }
}
